### ISSUE TITLE
Possibility of retrieving real public key

### ISSUE THREAD

**Issue by quantum13** [GetScatter/ScatterWebExtension#107]
We use scatter for login to our site (via `getArbitrarySignature`). Now workflow looks like (see https://staging.smartz.io/login):
- user selects identity for our site
- we get pub key from chosen identity
- user sign our message with this public key
- we check signed message

Minuses of this approach that we know only public key of identity, but not real public key from `key pairs`. So if something happens with identity (accidental removing) user will lost his account.

`getArbitrarySignature` supports passsing public key from `key pairs`, but it is not very convinient make user to type his public key during login. 

Could you please provide some interface for retrieveing public keys from `key pairs` with its names?

**Comment by wayne-prosperworks** [comment]
In our system, we want  to user to register their EOS account name with pubic key. It will be really useful if scatter   can expose the real public of  the account.   (scatter.identity.publicKey is not the account's public key).

**Comment by nsjames** [comment]
Public keys return for accounts in desktop.

Seeing how this extension will be deprecated soon, I'd advise checking out the `scatter-js` library in this same organization and upgrading to support desktop
