### ISSUE TITLE
Can't connect to jungle testnet

### ISSUE THREAD

**Issue by blockchain-expert** [GetScatter/ScatterWebExtension#120]
I'm trying to connect jungle test net with scatter. I've an account in test net. I've added its key pair. When I import it to identity it shows "no account exist for specified key". why this happens?

**Comment by nsjames** [comment]
Have you added the network inside of Scatter?

If you have; check if you added the `chainId` on either side. If you have then both sides must have it. 
`chainId` always overrides hosts.

**Comment by hershkoy** [comment]
@nsjames, I also have this issue.

Networks:
Name: jungles
http
Domain: jungle.cryptolions.io
Port:18888
ChainId: 038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca

After creating an identity, I am trying to click on the circle to get balances, "loading balances" appear for 1 second and disappears.
When inspecting, on the Network tab I see that scatter is using 
/v1/chain/get_table_rows => {"code": "eosio.token", "scope": "hezitester11", "table": "accounts", "limit": 5000}
which returns:
{"rows":[],"more":false}

I checked on http://jungle.cryptolions.io/#api, and I also get the same response there.
but if I do 
/v1/chain/get_account => {"account_name": "hezitester11"}
I get the correct response
{
  "account_name": "hezitester11",
  "head_block_num": 4836619,
  "head_block_time": "2018-07-09T23:20:27.000",
  "privileged": false,....
}

In addition, when trying to connect to scatter from websites like eostoolkit, I never see the identity that I created. not sure if it related.

Would appreciate any help. Thanks!

**Comment by hershkoy** [comment]
Loading balance now works (Ijust needed to add coins to the account from the faucet),
But I am still unable to connect scatter testnet identity to websites like eostoolkit, because it never shows the testnet identity.
Any idea?

**Comment by hershkoy** [comment]
![scatter_testnet](https://user-images.githubusercontent.com/13259380/42544628-98bd0a66-84bb-11e8-8d1a-549153853310.gif)

**Comment by hershkoy** [comment]
It was the chainId, which was hard coded in the code to be of the mainnet in the getIdentity request to scatter. 
My problem solved, don't know about the OP

**Comment by blockchain-expert** [comment]
Problem is with the host. I think there is some issue in connecting with jungle.cryptolions.io:18888. I changed the host to one I got from http://jungle.cryptolions.io/#p2p. Thus Issue solved.
