### ISSUE TITLE
[bug] chainid is not injected eosjs

### ISSUE THREAD

**Issue by str** [GetScatter/ScatterWebExtension#128]
When calling `scatter.eos()` you need to set the chainId as eosOptions like this:

```
const eosOptions = {
    chainId: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
};
const eos     = scatter.eos( network, Eos, eosOptions, 'http' );
const backend = eos.contract('eosforumtest');
```

If you don't you get the following error message:

```
chainId mismatch, signatures will not match transaction authority. expected 
cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f 
!== actual 
aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906

@ eos.min.js:1:7998
```

**Comment by seant-ca** [comment]
Yes, the Developer documentation should be updated accordingly.

**Comment by nsjames** [comment]
Fixed on both Scatter Classic and Scatter Desktop.

**Comment by str** [comment]
OK, I double checked in Chrome and there it works now without the chainID, even without the authorization param. W00T!! 

... but only for Chrome. Is Firefox still going to be supported, or what's the future for that plugin?
