### ISSUE TITLE
How to sign mix contracts transaction with Scatter

### ISSUE THREAD

**Issue by pandafunx** [GetScatter/ScatterWebExtension#130]
Hello James,

In eosjs GitHub (https://github.com/EOSIO/eosjs#calling-actions) , here support mix contracts in the same contracts. like below:

// mix contracts in the same transaction
await eos.transaction(['myaccount', 'eosio.token'], ({myaccount, eosio_token}) => {
  myaccount.transfer('inita', 'initb', '1.000 TOK@myaccount', '')
  eosio_token.transfer('inita', 'initb', '1.0000 SYS', '')
})

and it's very pleasure if u can support it in Scatter, since this is very useful feature to Dapps.

Thanks
Panda.X team

**Comment by docloulou** [comment]
+1

**Comment by infohata** [comment]
22 days and no response? @nsjames - this is a serious issue.

**Comment by nsjames** [comment]
fefc86f1195045c89230ebcbc09d9a4bed2e9780

**Comment by iFrankWu** [comment]
Thanks @nsjames ，I'll test it later.
