### ISSUE TITLE
How to call an action that required `eosio.code` authorization?

### ISSUE THREAD

**Issue by Falci** [GetScatter/ScatterWebExtension#131]
My action will move EOS token in the behavior of the user.
Locally, I'm setting account permission with: 
```
cleos set account permission user active '{"threshold": 1,"keys": [{"key": "EOS_contract_owner_public_key","weight": 1}],"accounts": [{"permission":{"actor":"contract_owner","permission":"eosio.code"},"weight":1}]}' owner -p user
```
It's enought to make it work from the command line;

How can I do it using Scatter and EosJS?

**Comment by nsjames** [comment]
Please add a ticket to eosjs instead, as this is not related to Scatter.

https://github.com/EOSIO/eosjs
