### ISSUE TITLE
Cache for get_code still does not work, it's terribly slow, please help!

### ISSUE THREAD

**Issue by lhzw** [GetScatter/ScatterWebExtension#133]
scatter version: 6.1.3, chrome: 67.0.3396.79
![image](https://user-images.githubusercontent.com/17211510/42496325-361f14de-8458-11e8-8598-0ab6f1d72b25.png)

**Comment by nsjames** [comment]
Those are from eosjs and not Scatter.

Scatter caches the ABIs internally but those caches are only one of many that eosjs already does.
Please refer to this issue: https://github.com/EOSIO/eosjs/issues/208

**Comment by nsjames** [comment]
On another note, a way to combat this is caching your `eos.contract(...)` method and reusing it.
