### ISSUE TITLE
Does scatter support set account eosio.code permission?

### ISSUE THREAD

**Issue by lhzw** [GetScatter/ScatterWebExtension#134]
How to do it if it supports, thank you very much.

**Comment by lhzw** [comment]
Oh sorry, I searched the cache, forgot to search this one.

To help the users to give the eosio.code permission to our contract, then we can call action...send() in the contract. Or we have to do the transaction outside, not in the contract, not a good one from our viewpoint.

**Comment by nsjames** [comment]
Users don't provide the eosio.code permission, you add it to your contract.
