### ISSUE TITLE
Upload extension to AMO

### ISSUE THREAD

**Issue by Powersource** [GetScatter/ScatterWebExtension#137]
i.e. the firefox addon website.  
It seems you have support for Firefox already (https://github.com/GetScatter/ScatterWebExtension/issues/20), is anything else blocking this?

**Comment by nsjames** [comment]
Scatter was actually on AMO for quite a while until they decided one day that being open source with clear instructions for compilation wasn't enough and required that Scatter be double-uploaded to their proprietary version control system for automatic checks. 

Firefox extensions will only be available for the new Light Web Extension which interacts with the Scatter Desktop application, and not with Scatter Classic

**Comment by str** [comment]
So, let me see if I understand it right. FF is being deprecated, because you don't have time to upload the project to their source control system. Do you need some help? How can we contribute to support FF too?
