### ISSUE TITLE
Allow connecting from other extensions

### ISSUE THREAD

**Issue by Powersource** [GetScatter/ScatterWebExtension#138]
We [are considering](https://github.com/SuperuserLabs/thankful/issues/86) using Scatter instead of MetaMask but at the moment we can't since afaict only websites can use Scatter, not web extensions. MetaMask has [support for this](https://github.com/MetaMask/metamask-extension/pull/3997) even if it's pretty hacky so far.

**Comment by nsjames** [comment]
This will not be supported from within this "Scatter Classic" extension, but can be supported through the Scatter Desktop extension. 

https://github.com/GetScatter/ScatterDesktop

There is no documentation for this yet, but working example code is used in the new light extension that connects with the desktop app: 
https://github.com/GetScatter/ScatterWebConnector/blob/master/src/services/SocketService.js
