### ISSUE TITLE
Additional requests while preparing transaction

### ISSUE THREAD

**Issue by sim31** [GetScatter/ScatterWebExtension#139]
When making eos.transaction() call with eos returned from scatter it makes a bunch of get_info/get_block/get_abi requests:
![image](https://user-images.githubusercontent.com/7878290/42923787-0b42270e-8b30-11e8-9172-f295b5d869c1.png)

When using eosjs@15.0.6 directly, however it's much better:
![image](https://user-images.githubusercontent.com/7878290/42923849-4cb9ddb2-8b30-11e8-8cf7-fd4c22ab434b.png)

Plus I was able to reduce additional requests to just only one get_abi call, by providing transaction headers myself. Through scatter only one get_block request is saved this way.

Is where anyway to reduce the overhead?

Btw, does scatter have it's own version of eosjs which it uses? Because it looks a lot like [this issue](https://github.com/EOSIO/eosjs/issues/208), which appears to be almost fixed in newest eosjs.

**Comment by nsjames** [comment]
I'd suggest tagging onto the ticket I created on eosjs (https://github.com/EOSIO/eosjs/issues/208). There's really nothing Scatter can do about this. Scatter already caches ABIs on our side but all those requests are coming from eosjs alone. I agree, it's a problem which needs a solution.

**Comment by sim31** [comment]
Why I don't see that many unnecessary requests when using eosjs directly?
