### ISSUE TITLE
How to do Backup Restoration?

### ISSUE THREAD

**Issue by MikeD10375** [GetScatter/ScatterWebExtension#140]
I had to clean install my OS. How do I restore Scatter Wallet from backup? I have my password and recovery words. I'm using the Chrome extension.

**Comment by nsjames** [comment]
Seed phrase / mnemonic is only a replacement for your password, not a backup of your Scatter. 
You need to have backed up your Scatter from the settings menu which will export an encrypted JSON of your Scatter that can be imported.
