### ISSUE TITLE
Error when not passing in 'chainId' to scatter.eos

### ISSUE THREAD

**Issue by yagottahavehart** [GetScatter/ScatterWebExtension#144]
Scatter 6.1.5
Eosjs 16.0.0

```
 const network = {
          blockchain:'eos',
          host: 'localhost',
          port:8888
}

// scatter.getIdentity({accounts:[ network ]}).then(identity => {
const eos = scatter.eos( network, Eos, {});

// eos.contract('foo').then(contract => { ... 
contract.bar(account.name, 'baz', { authorization: [`${account.name}@${account.authority}`] });
```

results in error: `options is not defined` which appears to refer to 
https://github.com/GetScatter/ScatterWebExtension/blob/master/src/plugins/defaults/eos.js#L153

Before the extension update, the above code resulted in a correct eos connection. Now, I get that error. If I throw a chainId in there (only seems to support default `cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f`) it goes through but I get an 'Missing required accounts, repull the identity, 402' error when calling contracts that previously succeeded.

Any thoughts?

**Comment by nsjames** [comment]
Hmm should have been backwards compatible but indeed there was a change there.
You'll need to update that code to put the chainId inside of the network ( it should always be there anyway )

**Comment by nsjames** [comment]
Oh actually yeah there's a typo there. Should have been `_options`

**Comment by nsjames** [comment]
e2015d8cd610394d5289c6eb551fc7ccb82f56f0 not yet pushed to chrome store
