### ISSUE TITLE
How to detect the presence of Scatter on page load?

### ISSUE THREAD

**Issue by acoutts** [GetScatter/ScatterWebExtension#145]
I can always check the window.scatter reference after a timeout, but is there a more reliable way to check if Scatter is installed?

**Comment by str** [comment]
```
document.addEventListener('scatterLoaded', scatterExtension => {
    const scatter = window.scatter;
    window.scatter = null;
    callYourCallback(scatter);
 });
```

**Comment by acoutts** [comment]
I do that but won't that CB only execute if the scatterLoaded event fires?

What I'm looking for is a way to detect when that *doesn't* work, perhaps the timeout I'm using is the best option but I wanted to see what else was available.

**Comment by nsjames** [comment]
Yup, only a timeout.  Scatter can't tell you that it doesn't exist.
