### ISSUE TITLE
6.1.6 bugs, unstable

### ISSUE THREAD

**Issue by lhzw** [GetScatter/ScatterWebExtension#149]
6.1.3 is fine!! Please don't push unstable update to us.

![image](https://user-images.githubusercontent.com/17211510/43560793-c58a7aa0-9646-11e8-9010-b9f60ba2c9ed.png)

**Comment by nsjames** [comment]
Ouch, had fixed that the same day but forgot to push it to chrome store. 
Pushed, apologies.
