### ISSUE TITLE
Wrong window sizing

### ISSUE THREAD

**Issue by bitcoiners** [GetScatter/ScatterWebExtension#156]
When using Scatter often popup does not size properly and part of it is not visible.

![image](https://user-images.githubusercontent.com/38520/44445813-ad2c9a80-a60c-11e8-8374-04499db2625a.png)

**Comment by bitcoiners** [comment]
Will this issue be addressed? On Ubuntu 18.04 Scatter popup windows are undersised and part of the screen is not visible.

**Comment by nsjames** [comment]
This project is deprecated and unmaintained. Please switch to using Scatter Desktop.

**Comment by bitcoiners** [comment]
Not all websites support Scatter Desktop. For example https://eosweb.net/ram

**Comment by nsjames** [comment]
Let them know they are putting your security at risk, and that they should update.
