### ISSUE TITLE
Does demos.scatter-eos.com still work?

### ISSUE THREAD

**Issue by MarcelBlockchain** [GetScatter/ScatterWebExtension#157]
Does demos.scatter-eos.com still work? Tells me 'requires EOS Account' although I have imported a working one. 
Using in dev mode, chrome, mac os high sierra.
npm install, copied the .env, npm start. Imported the privkey of my working account. Should work, right?

**Comment by nsjames** [comment]
It does not in fact. It was only for testing for the 6 months before the mainnet launched since there was no consistent public endpoint during that period.
