### ISSUE TITLE
Scatter not loading from backup

### ISSUE THREAD

**Issue by Jam3sMacduff** [GetScatter/ScatterWebExtension#162]
I'm using scatter desktop app on windows 7 but it doesn't work with some sites (such as eostoolkit.io) which needs the chrome extension. When I add the extension and try to load my scatter from a backup it asks for my password / seed but doesn't recognise either. Same error message - password must be at least 8 characters... Anyone had the same issue / figured out a workaround?

**Comment by slaphead** [comment]
I am having the same issue on Windows 10. I assume you paste the backup text in the json file and then enter in the password created using the desktop app? It keeps showing the error bad password. I use the same password to login on the desktop and it is fine. Please assist here as I cannot trust this app if backups cannot be restored.

**Comment by nsjames** [comment]
Stop using extension. It is deprecated. Move to desktop. 
Also backups are not compatible between the two.


> I'm using scatter desktop app on windows 7 but it doesn't work with some sites (such as eostoolkit.io) 
EOS Toolkit does support desktop.
