### ISSUE TITLE
"There is no identity with an account set on your Scatter instance.", Error with scatter-js

### ISSUE THREAD

**Issue by johanninos** [GetScatter/ScatterWebExtension#178]
with **ScatterWebExtension(Scatter Classic)**

get Error 
```javascript
 {
     type: "There is no identity with an account set on your Scatter instance.",
     message: undefined,
     code: 423,
     isError: true
}
```
when fire `authenticate()` or `logout()` after `getIdentity()`

```javascript
await scatter.getIdentity({
    accounts:[network]
})

scatter.authenticate('something').then(res => console.log(res))
```

with **Scatter Desktop**  it works 

```javascript
await scatter.getIdentity({
    accounts:[network]
})
```

reload()

```javascript
scatter.authenticate('something').then(res => console.log(res))
```
`authenticate()` also works after reload page

**Comment by mlockett42** [comment]
I have been having a similar issue over the last few days with scatterdesktop.

I updated all of my requirements and explicitly supplied the signing authorisation and it started working again

see https://github.com/eosphere/eos-voter/commit/55f48edaa0c73a8d30ef8833a60374c401fc4531

**Comment by nsjames** [comment]
Closing in favor of https://github.com/GetScatter/scatter-js/issues/82
