### ISSUE TITLE
How to deal with forget password and phrase?

### ISSUE THREAD

**Issue by wangyilin1987** [GetScatter/ScatterWebExtension#179]
i forget pasword,and  want new a scatter,but have no entrance to renew a scatter.

**Comment by nsjames** [comment]
This project has been deprecated for almost a year. Please move to Desktop.

To erase all data though just remove the extension from `chrome://extensions` and then add it again.

**Comment by wangyilin1987** [comment]
thank you, my question is Desktop's .and  i just in ScatterDesktop Find the answer.
