### ISSUE TITLE
Identities and deploying contracts

### ISSUE THREAD

**Issue by quantum13** [GetScatter/ScatterWebExtension#74]
Hi, we use scatter for deploing contracts to blockchain
But when we call
```
    scatter
    .eos(..)
    .setcode(accountName, 0, 0, wast);
```
it works only if accountName is the account from identity.

But it not very convenient since user must create new identity for all account for deploed smart contracts.

I see several solutions:
- allow scatter to add several accounts to one identity (identity.accounts is already array)
- scatter should allow deploy contracts to all accounts which belong keys of account from identity

What do you think?

**Comment by nsjames** [comment]
Hmm. You might be better off using the `requestArbitrarySignature` instead as it will look for keys instead of identities. Can one of you try this out and see how that flow works?

With that being said, there is an internal ticket about adding the ability to have multiple EOS accounts within the same identity and network. That would definitely solve this as well.

**Comment by quantum13** [comment]
Using `requestArbitrarySignature` is not very good idea at this case since user won't see what exactly he sign (with standard flow he at least see that we request sign method `setcode`)

Looking forward to implementation of ability to having multiple accounts in identity

**Comment by nsjames** [comment]
True, but I wouldnt really expect this to be used by "users", but developers.

What's the use case for users?

**Comment by nsjames** [comment]
Ah, I see.
So you guys might have to wait for the multi-account update.

**Comment by changhao88** [comment]
Re : meaning of every buttons 

I have a suggestion. There are buttons when use Scatter. When we touch every buttons by using mouse, if shows the meaning of button before click, it will be convenient.

For example, when we touch (not click) a button by using mouse, it shows <save> or <close>, etc.

Thanks for Scatter team ^^*

**Comment by Another-Joe** [comment]
Looking forward to it.

**Comment by nsjames** [comment]
Move to Scatter Desktop with scatter-js. It has multi-account support.
